import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { Loader2, Plus, Sparkles, Trash2 } from "lucide-react";
import { useState } from "react";

import { AppLayout } from "@/components/app/AppLayout";
import { MonthCalendarOutput } from "@/components/app/MonthCalendarOutput";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { generatePlan } from "@/lib/assistant.functions";

export const Route = createFileRoute("/planner")({
  head: () => ({
    meta: [
      { title: "AI Task Planner | Workplace AI Assistant" },
      {
        name: "description",
        content:
          "Turn a messy task list into a prioritised, time-blocked daily schedule with delegation notes for managers.",
      },
      { property: "og:title", content: "AI Task Planner | Workplace AI Assistant" },
      {
        property: "og:description",
        content: "Prioritised managerial tasks and a time-blocked schedule, generated by AI.",
      },
    ],
  }),
  component: PlannerPage,
});

const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

type TaskRow = { day: string; task: string };

function PlannerPage() {
  const run = useServerFn(generatePlan);
  const now = new Date();
  const [role, setRole] = useState("");
  const [workHours, setWorkHours] = useState("09:00 - 17:00");
  const [month, setMonth] = useState(MONTHS[now.getMonth()]!);
  const [year, setYear] = useState(String(now.getFullYear()));
  const [rows, setRows] = useState<TaskRow[]>([
    { day: "1", task: "" },
    { day: "", task: "" },
  ]);
  const [output, setOutput] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const years = [now.getFullYear() - 1, now.getFullYear(), now.getFullYear() + 1].map(String);

  const setRow = (index: number, patch: Partial<TaskRow>) =>
    setRows((prev) => prev.map((r, i) => (i === index ? { ...r, ...patch } : r)));

  const tasksText = rows
    .filter((r) => r.task.trim())
    .map((r) => `Day ${r.day.trim() || "unassigned"} | ${r.task.trim()}`)
    .join("\n");

  const generate = async () => {
    if (tasksText.trim().length < 3) {
      setError("Add at least one task, meeting or deadline.");
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const result = await run({ data: { role, workHours, tasks: tasksText, month, year } });
      setOutput(result.text);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const submit = (event: React.FormEvent) => {
    event.preventDefault();
    void generate();
  };

  return (
    <AppLayout
      title="AI Task Planner"
      description="Prioritise managerial work and build a realistic month plan."
    >
      <div className="grid gap-6 xl:grid-cols-2">
        <form onSubmit={submit} className="surface-card space-y-5 p-5 md:p-6">
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="role">Your role</Label>
              <Input
                id="role"
                value={role}
                onChange={(e) => setRole(e.target.value)}
                placeholder="e.g. Operations Manager"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="hours">Working hours</Label>
              <Input
                id="hours"
                value={workHours}
                onChange={(e) => setWorkHours(e.target.value)}
                placeholder="09:00 - 17:00"
              />
            </div>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Label>Month plans are for</Label>
              <Select value={month} onValueChange={setMonth}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {MONTHS.map((m) => (
                    <SelectItem key={m} value={m}>
                      {m}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Year</Label>
              <Select value={year} onValueChange={setYear}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {years.map((y) => (
                    <SelectItem key={y} value={y}>
                      {y}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="space-y-2">
            <Label>Tasks, meetings and deadlines</Label>
            <div className="grid grid-cols-[4.5rem_1fr_2.5rem] gap-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              <span>Day</span>
              <span>Task / meeting / deadline</span>
              <span className="sr-only">Remove</span>
            </div>
            {rows.map((row, index) => (
              <div key={index} className="grid grid-cols-[4.5rem_1fr_2.5rem] items-center gap-2">
                <Input
                  value={row.day}
                  onChange={(e) => setRow(index, { day: e.target.value })}
                  inputMode="numeric"
                  placeholder="12"
                  aria-label={`Day for task ${index + 1}`}
                />
                <Input
                  value={row.task}
                  onChange={(e) => setRow(index, { task: e.target.value })}
                  placeholder="Board deck due 09:00"
                  aria-label={`Task ${index + 1}`}
                />
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  aria-label={`Remove task ${index + 1}`}
                  onClick={() => setRows((prev) => prev.filter((_, i) => i !== index))}
                  disabled={rows.length === 1}
                >
                  <Trash2 className="size-4" />
                </Button>
              </div>
            ))}
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => setRows((prev) => [...prev, { day: "", task: "" }])}
            >
              <Plus className="size-4" />
              Add row
            </Button>
          </div>

          <Button type="submit" size="lg" className="w-full" disabled={loading}>
            {loading ? <Loader2 className="size-4 animate-spin" /> : <Sparkles className="size-4" />}
            {loading ? "Building your month..." : "Generate monthly plan"}
          </Button>
        </form>

        <MonthCalendarOutput
          value={output}
          onChange={setOutput}
          onReset={() => setOutput("")}
          onRegenerate={() => void generate()}
          filename="monthly-plan.md"
          isLoading={loading}
          error={error}
          month={MONTHS.indexOf(month)}
          year={Number(year)}
          emptyHint="Add your tasks with their days and your editable month calendar appears here."
        />
      </div>
    </AppLayout>
  );
}