import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { Loader2, Sparkles } from "lucide-react";
import { useState } from "react";

import { AppLayout } from "@/components/app/AppLayout";
import { OutputPanel } from "@/components/app/OutputPanel";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { generatePlan } from "@/lib/assistant.functions";

export const Route = createFileRoute("/planner")({
  head: () => ({
    meta: [
      { title: "AI Task Planner | Workplace AI Assistant" },
      {
        name: "description",
        content:
          "Turn a messy task list into a prioritised, time-blocked daily schedule with delegation notes for managers.",
      },
      { property: "og:title", content: "AI Task Planner | Workplace AI Assistant" },
      {
        property: "og:description",
        content: "Prioritised managerial tasks and a time-blocked schedule, generated by AI.",
      },
    ],
  }),
  component: PlannerPage,
});

function PlannerPage() {
  const run = useServerFn(generatePlan);
  const [role, setRole] = useState("");
  const [workHours, setWorkHours] = useState("09:00 - 17:00");
  const [focus, setFocus] = useState("");
  const [tasks, setTasks] = useState("");
  const [output, setOutput] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (tasks.trim().length < 3) {
      setError("Add at least one task, meeting or deadline.");
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const result = await run({ data: { role, workHours, tasks, focus } });
      setOutput(result.text);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <AppLayout
      title="AI Task Planner"
      description="Prioritise managerial work and build a realistic time-blocked day."
    >
      <div className="grid gap-6 xl:grid-cols-2">
        <form onSubmit={submit} className="surface-card space-y-5 p-5 md:p-6">
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="role">Your role</Label>
              <Input
                id="role"
                value={role}
                onChange={(e) => setRole(e.target.value)}
                placeholder="e.g. Operations Manager"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="hours">Working hours</Label>
              <Input
                id="hours"
                value={workHours}
                onChange={(e) => setWorkHours(e.target.value)}
                placeholder="09:00 - 17:00"
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="focus">Most important outcome today (optional)</Label>
            <Input
              id="focus"
              value={focus}
              onChange={(e) => setFocus(e.target.value)}
              placeholder="Sign off the vendor contract"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="tasks">Tasks, meetings and deadlines</Label>
            <Textarea
              id="tasks"
              value={tasks}
              onChange={(e) => setTasks(e.target.value)}
              placeholder={
                "- Board deck due tomorrow 09:00\n- 1:1 with Thabo (30 min)\n- Approve leave requests\n- Review supplier quotes\n- Team standup 10:00"
              }
              className="min-h-48"
            />
          </div>

          <Button type="submit" size="lg" className="w-full" disabled={loading}>
            {loading ? <Loader2 className="size-4 animate-spin" /> : <Sparkles className="size-4" />}
            {loading ? "Building your day..." : "Generate daily plan"}
          </Button>
        </form>

        <OutputPanel
          value={output}
          onChange={setOutput}
          onReset={() => setOutput("")}
          filename="daily-plan.md"
          isLoading={loading}
          error={error}
          emptyHint="Paste your task list and your prioritised, editable schedule appears here."
        />
      </div>
    </AppLayout>
  );
}